name: Report Match

on: 
  workflow_dispatch:
    inputs:
      winner_name:
        description: 'Winner'
        required: true
        type: choice
        options:
          - 'Modi'
          - 'Pradyot'
      loser_name:
        description: 'Loser'
        required: true
        type: choice
        options:
          - 'Modi'
          - 'Pradyot'
      match_length:
        description: 'Length'
        default: '5'
        required: true
        type: choice
        options:
          - '1'
          - '3'
          - '5'
          - '7'
          - '9'
          - '11'
          - '13'
          - '15'
          - '17'
          - '19'
          - '21'
          - '23'
          - '25'

jobs:
  process_action_match:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Get Match Info
        id: get_match
        uses: actions/github-script@v7
        with:
          script: |
            const datetime = new Date();
            const formattedDate = datetime.toISOString().split('T')[0];
            const inputs = context.payload.inputs
            var winner = inputs.winner_name;
            var loser = inputs.loser_name;
            const match_length = inputs.match_length;
            console.log(`____________________________`);
            console.log(`${ formattedDate } ${ winner } > ${ loser } ${ match_length }`);
            return `|${ formattedDate }|${ winner }|${ loser }|${ match_length }|`;
          
      - name: Add to Match List
        run: |
          echo ${{ steps.get_match.outputs.result }} >> "MatchList.md"
        
      - name: Update Rating List
        run: |
          echo "____________________________"
          echo ${{ steps.get_match.outputs.result }}
          cd ./bigelo
          chmod +x ./bigeloLin
          ./bigeloLin
          echo "Updated Rating List!"

      - name: Commit Changes
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add 'MatchList.md'
          git add 'RatingList.md'
          git add 'README.md'
          git commit -m '${{ steps.get_match.outputs.result }}'
          git push
