name: Report Match Action

on: 
  repository_dispatch: 
    types: [match_report]    

jobs:
  process_action_match:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Get Match Info
        id: get_match
        uses: actions/github-script@v7
        with:
          script: |
            const datetime = new Date();
            const formattedDate = datetime.toISOString().split('T')[0];
            const winner = `${{ github.event.client_payload.winner_name }}`;
            const loser = `${{ github.event.client_payload.loser_name }}`;
            const match_length = `${{ github.event.client_payload.match_length }}`;
            console.log(`____________________________`);
            console.log(`${ formattedDate } ${ winner } > ${ loser } ${ match_length }`);
            return `|${ formattedDate }|${ winner }|${ loser }|${ match_length }|`;
          
      - name: Add to Match List
        run: |
          echo ${{ steps.get_match.outputs.result }} >> "MatchList.md"
        
      - name: Update Rating List
        run: |
          echo "____________________________"
          echo ${{ steps.get_match.outputs.result }}
          cd ./bigelo
          chmod +x ./bigeloLin
          ./bigeloLin
          echo "Updated Rating List!"

      - name: Commit Changes
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add 'MatchList.md'
          git add 'RatingList.md'
          git add 'README.md'
          git commit -m '${{ steps.get_match.outputs.result }}'
          git push
